DriveHappy/DriveHappy.Web/Controllers/OwnerController.cs
using DriveHappy.Data.ViewModel;
using DriveHappy.Service.Services;
using DriveHappy.Web.CustomAuthentication;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DriveHappy.Interface.IServices;
using System.Web.Security;
using System.Web.Script.Serialization;

namespace DriveHappy.Web.Controllers
{
    [Authorize]
    [OwnerAuthorizeFilter]
    public class OwnerController : Controller
    {
        private IOwnerServices OwnerService;
        private ICommonServices CommonService;
        /// <summary>
        /// Initializes a new instance of the <see cref="OwnerController"/> class.
        /// </summary>
        public OwnerController()
        {
            OwnerService = new OwnerServices();
            CommonService = new CommonServices();
        }

        /// <summary>
        /// Mies the cars.
        /// </summary>
        /// <returns>partial view for the Owner Car listing</returns>
        public ActionResult MyCars()
        {
            List<CarViewModel> listCarViewModel = new List<CarViewModel>();
            listCarViewModel = OwnerService.GetCar((int)Session["UserId"]);
            return PartialView("_MyCars", listCarViewModel);
        }

        /// <summary>
        /// Noes the car added.
        /// </summary>
        /// <returns>Partial view for the Owner when no car are added</returns>
        public ActionResult NoCarAdded()
        {
            return PartialView("_NoCarAdded");
        }

        /// <summary>
        /// Cars the data.
        /// </summary>
        /// <returns>partial view for the Car Details entering option</returns>
        public ActionResult CarData()
        {
            return PartialView("_CarData");
        }

        /// <summary>
        /// Validates the date.
        /// </summary>
        /// <param name="ownerCarViewModel">The ownerCarViewModel.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ValidateDate(OwnerCarViewModel ownerCarViewModel)
        {
            string dateStatus = CommonService.ValidateDate(ownerCarViewModel.FromDate, ownerCarViewModel.ToDate);
            Dictionary<string, object> message = new Dictionary<string, object>();
            JsonResult result = new JsonResult();
            if(dateStatus.Equals("success"))
            {
                message.Add("code", 200);
                message.Add("success", dateStatus);
            }
            else
            {
                message.Add("code", 406);
                message.Add("error", dateStatus);
                Response.StatusCode = 406;
                Response.SuppressFormsAuthenticationRedirect = true;
            }
            result = Json(message, JsonRequestBehavior.AllowGet);
            return result;
        }

        /// <summary>
        /// Validates the owner car data.
        /// </summary>
        /// <param name="ownerCarViewModel">The ownerCarViewModel.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ValidateOwnerCarData(OwnerCarViewModel ownerCarViewModel)
        {
            string carStatus = CommonService.ValidateCarDetails(ownerCarViewModel);
            Dictionary<string, object> message = new Dictionary<string, object>();
            JsonResult result = new JsonResult();
            if (carStatus.Equals("success"))
            {
                message.Add("code", 200);
                message.Add("success", carStatus);
            }
            else
            {
                message.Add("code", 406);
                message.Add("error", carStatus);
                Response.StatusCode = 406;
                Response.SuppressFormsAuthenticationRedirect = true;
            }
            result = Json(message, JsonRequestBehavior.AllowGet);
            return result;
        }

        /// <summary>
        /// Validates the location.
        /// </summary>
        /// <param name="ownerCarViewModel">The ownerCarViewModel.</param>
        /// <returns>json result if location is valid of not</returns>
        [HttpPost]
        public ActionResult ValidateLocation(OwnerCarViewModel ownerCarViewModel)
        {
            string locationStatus = CommonService.ValidateLocation(ownerCarViewModel);
            Dictionary<string, object> message = new Dictionary<string, object>();
            JsonResult result = new JsonResult();
            if (locationStatus.Equals("success"))
            {
                message.Add("code", 200);
                message.Add("success", locationStatus);
            }
            else
            {
                message.Add("code", 406);
                message.Add("error", locationStatus);
                Response.StatusCode = 406;
                Response.SuppressFormsAuthenticationRedirect = true;
            }
            result = Json(message, JsonRequestBehavior.AllowGet);
            return result;
        }

        /// <summary>
        /// Owners the car add.
        /// </summary>
        /// <param name="ownerCarViewModel">The owner car view model.</param>
        /// <returns>json result</returns>
        public ActionResult OwnerCarAdd(OwnerCarViewModel ownerCarViewModel)
        {
            Dictionary<string, object> message = new Dictionary<string, object>();
            JsonResult result = new JsonResult();
            string validateMessage = CommonService.ValidateOwnerCarData(ownerCarViewModel);
            if(validateMessage.Equals("success"))
            {
                ownerCarViewModel.UserId = (int)Session["UserId"];
                string statusMessage = OwnerService.AddOwnerCar(ownerCarViewModel);
                if(statusMessage.Equals("success"))
                {
                    message.Add("code","200");
                    message.Add("success","success");
                    result = Json(message, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    message.Add("code","406");
                    Response.StatusCode = 406;
                    message.Add("error", statusMessage);
                    result = Json(message, JsonRequestBehavior.AllowGet);
                    Response.SuppressFormsAuthenticationRedirect = true;
                }
                return result;
            }
            else
            {
                message.Add("code","406");
                Response.StatusCode = 406;
                message.Add("error", validateMessage);
                result = Json(message, JsonRequestBehavior.AllowGet);
                Response.SuppressFormsAuthenticationRedirect = true;
                return result;
            }
        }

        /// <summary>
        /// Gets the car brand.
        /// </summary>
        /// <param name="brandHint">The brand hint.</param>
        /// <returns>Json result contain list of brand name</returns>
        public ActionResult GetCarBrand(string BrandHint)
        {
            Dictionary<string, object> message = new Dictionary<string, object>();
            JsonResult result = new JsonResult();
            List<string> brandNames = null;
            if(CommonServices.IsAlphaNumeric(BrandHint))
            {
                if (BrandHint.Length > 1)
                {
                    brandNames = OwnerService.GetBrandNameList(BrandHint);
                    if((brandNames != null) && (brandNames.Count > 0))
                    {
                        message.Add("code", 200);
                        message.Add("correct", brandNames);
                    }
                    else
                    {
                        Response.StatusCode = 404;
                        Response.SuppressFormsAuthenticationRedirect = true;
                        message.Add("code", 404);
                        message.Add("error", "Page not found");
                    }
                }
                else
                {
                    Response.StatusCode = 404;
                    Response.SuppressFormsAuthenticationRedirect = true;
                    message.Add("code", 404);
                    message.Add("error", "Page not found");
                }
            }
            else
            {
                Response.StatusCode = 404;
                Response.SuppressFormsAuthenticationRedirect = true;
                message.Add("code", 400);
                message.Add("error", "Dangerous Request");
            }
            result = Json(message, JsonRequestBehavior.AllowGet);
            return result;
        }

        /// <summary>
        /// Gets the car model.
        /// </summary>
        /// <param name="ModelHint">The model hint.</param>
        /// <param name="BrandName">Name of the brand.</param>
        /// <returns>List of Model name having hint as Model hint of the specified Brand Name</returns>
        public ActionResult GetCarModel(string ModelHint, string BrandName)
        {
            Dictionary<string, object> message = new Dictionary<string, object>();
            JsonResult result = new JsonResult();
            List<string> modelNames = null;
            if ((CommonServices.IsAlphaNumeric(BrandName)) && (CommonServices.IsAlphaNumeric(ModelHint)))
            {
                if (ModelHint.Length > 0)
                {
                    modelNames = OwnerService.GetModelNameList(ModelHint, BrandName);
                    if ((modelNames != null) && (modelNames.Count > 0))
                    {
                        message.Add("code", 200);
                        message.Add("correct", modelNames);
                    }
                    else
                    {
                        Response.StatusCode = 404;
                        Response.SuppressFormsAuthenticationRedirect = true;
                        message.Add("code", 404);
                        message.Add("error", "Page not found");
                    }
                }
                else

DriveHappy/DriveHappy.Web/Views/Owner/_CarCardView.cshtml
@model DriveHappy.Data.ViewModel.CarViewModel
<div class="for-height"></div>
<div class="car-card-view col-md-4 col-sm-6 col-xs-12">
    <div class="wrapper">
        <div class="car-card-view-head container-fluid" style="background-image:url(@Model.CarPath)">
            <div class="overlay-card-view-head col-xs-12 clear-padding">
                <div class="car-card-view-head-content col-xs-12">
                    <div class="col-xs-4 clear-padding">
                        <small class="car-card-model car-card-content">@Model.CarName.ToUpper()</small>
                    </div>
                    <div class="car-card-seater-wrapper col-xs-6 col-xs-offset-2 clear-padding">
                        <img src="~/Content/AdminImage/safety-seat.png" class="car-card-ico" />
                        <div class="car-card-seater-div">
                            <small class="car-card-seater car-card-content">@Model.Seater</small>
                        </div>
                    </div>
                    <div class="col-xs-4 clear-padding">
                        <small class="car-card-brand car-card-content">@Model.BrandName.ToUpper()</small>
                    </div>
                </div>
            </div>
        </div>
        <div class="car-card-view-body container-fluid">
            <div class="car-card-body-content col-xs-12 clear-padding">
                <img src="~/Content/AdminImage/petrol.png" class="car-card-body-ico" />
                <small class="car-card-fuel car-card-body-input-content">@Model.FuelType.ToUpper()</small>
            </div>
            <div class="car-card-body-content col-xs-12 clear-padding">
                <img src="~/Content/AdminImage/driving-gear-controls.png" class="car-card-body-ico" />
                <small class="car-card-transmission car-card-body-input-content">@Model.Transmission.ToUpper()</small>
            </div>
        </div>
        <div class="car-card-view-footer container-fluid">
            <div class="col-xs-12 clear-padding">
                <small class="car-card-category car-card-footer-input-content">@Model.CarCategory.ToUpper()</small>
            </div>
        </div>
    </div>
</div>

DriveHappy/DriveHappy.Web/Views/Owner/_CarData.cshtml
@model DriveHappy.Data.ViewModel.OwnerCarViewModel

<div class="car-data container-fluid">
    <div class="car-data-content col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
        <div class="car-add-head col-xs-12">
            Five Simple step to add your car
        </div>
        <div class="close-owner-car-add">
            <span>&times;</span>
        </div>
        <div class="car-add-body col-xs-12" data-tab="0">
            <div class="car-add-body-head col-xs-12 clear-padding">
                <div class="abs-horizontal-line"></div>
                <div class="col-xs-2  col-xs-offset-1 clear-padding">
                    <div class="form-circle active-form-circle">
                        <span class="fa fa-calendar "></span>
                    </div>
                </div>
                <div class="clock col-xs-2 clear-padding">
                    <div class="form-circle clock">
                        <span class="fa fa-clock-o"></span>
                    </div>
                </div>
                <div class="col-xs-2 clear-padding">
                    <div class="form-circle money">
                        <span class="fa fa-money"></span>
                    </div>
                </div>
                <div class="col-xs-2 clear-padding">
                    <div class="form-circle about-car">
                        <span class="fa fa-cab"></span>
                    </div>
                </div>
                <div class="col-xs-2 clear-padding">
                    <div class="form-circle Location">
                        <span class=" fa fa-map-marker"></span>
                    </div>
                </div>
            </div>
            @using (Html.BeginForm("OwnerCarAdd", "Owner", FormMethod.Post, new { @id = "ownerCar", novalidate = "novalidate" }))
            {
                <div class="car-add-body-calender car-tab col-xs-12 clear-padding">
                    <div class="car-add-body-container-head col-xs-12">
                        Your Car Will Be Available To Us (Date)
                    </div>
                    <div class="DateStatusMessage">

                    </div>
                    <div class="calender col-xs-12">
                        <div class="from-calender col-xs-6">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.FromDate, new { required="required", @class="from-date input-content", id="mytarget"})
                                <label class="label-add">From Date</label>
                                <div class="monthly" id="mycalendar"></div>
                            </div>
                        </div>
                        <div class="to-calender col-xs-6">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.ToDate, new { required = "required", @class = "to-date input-content", id = "mytargetTo" })
                                <label class="label-add">To Date</label>
                                <div class="monthly" id="mycalendarTo"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="car-add-body-timming car-tab col-xs-12 clear-padding">
                    <div class="car-add-body-container-head col-xs-12">
                        Your Car Will Be Available To Us (Timing)
                    </div>
                    <div class="TimeStatusMessage">

                    </div>
                    <div class="calender col-xs-12">
                        <div class="from-timmer col-xs-6">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.FromTime, new { required = "required", @class = "from-time input-content timepicker", id = "timeFrom" })
                                <label class="label-add">From Time</label>
                            </div>
                        </div>
                        <div class="to-timmer col-xs-6">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.ToTime, new { required = "required", @class = "to-time input-content input-content timepicker", id = "timeTo" })
                                <label class="label-add">To Time</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="car-add-body-price car-tab col-xs-12 clear-padding">
                    <div class="car-add-body-container-head col-xs-12">
                        Your Car Pricing Structure
                    </div>
                    <div class="PriceStatusMessage">

                    </div>
                    <div class="calender col-xs-12">
                        <div class="hourly-pricing col-xs-4">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.HourlyPrice, new { required = "required", @class = "hourly-price input-content", id = "hourly-price" })
                                <label class="label-add">Hourly Price</label>
                            </div>
                        </div>
                        <div class="daily-pricing col-xs-4">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.DailyPrice, new { required = "required", @class = "daily-price input-content", id = "daily-price" })
                                <label class="label-add">Daily Price</label>
                            </div>
                        </div>
                        <div class="spl-day-pricing col-xs-4">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.SplDayPrice, new { required = "required", @class = "spl-day-price input-content", id = "spl-day-price" })
                                <label class="label-add">Holiday Price</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="car-add-body-car-data car-tab col-xs-12 clear-padding">
                    <div class="car-add-body-container-head col-xs-12">
                        Your Personal Car Data
                    </div>
                    <div class="CarStatusMessage">

                    </div>
                    <div class="calender col-xs-12">
                        <div class="plate-no col-xs-4">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.PlateNo, new { required = "required", @class = "plate-no-input input-content", id = "plate-no" })
                                <label class="label-add">Plate No</label>
                            </div>
                        </div>
                        <div class="car-brand col-xs-4">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.CarBrand, new { required = "required", @class = "car-brand-input input-content", id = "car-brand" })
                                <label class="label-add">Brand</label>
                            </div>
                            <div class="car-brand-hint">
                                
                            </div>
                        </div>
                        <div class="model-no col-xs-4">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.CarModel, new { required = "required", @class = "model-no-input input-content", id = "model-no" })
                                <label class="label-add">Model</label>
                            </div>
                            <div class="car-model-hint">

                            </div>
                        </div>
                    </div>
                </div>
                <div class="car-add-body-pick-in-point car-tab col-xs-12 clear-padding">
                    <div class="car-add-body-container-head col-xs-12">
                        Your Car Will Be Available At Location
                    </div>
                    <div class="LocationStatusMessage">

                    </div>
                    <div class="calender col-xs-12">
                        <div class="city col-xs-6">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.City, new { required = "required", @class = "city-input input-content", id = "car-add-city" })
                                <label class="label-add">City</label>
                            </div>
                        </div>
                        <div class="location col-xs-6">
                            <div class="form-control">
                                @Html.TextBoxFor(m => m.Location, new { required = "required", @class = "city-input input-content", id = "car-add-city" })
                                <label class="label-add">Location</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="car-add-footer col-xs-2 col-xs-offset-5">
                    <div class="next-ico" action-url="@Url.Action("OwnerCarAdd","Owner")">
                        <span class="fa fa-chevron-right"></span>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<script src="~/Scripts/CarDataScript.js"></script>

DriveHappy/DriveHappy.Web/Views/Owner/_MyCars.cshtml
@using DriveHappy.Data.ViewModel;
@model List<CarViewModel>

<div class="add-car-details col-xs-12 clear-padding">
    <button class="car-add-btn"><span class="fa fa-plus"></span></button>
    @if ((Model.Count) > 0)
    {
        Model.Reverse();
        foreach (var car in Model)
        {
            @Html.Partial("_CarCardView", car)
        }
    }
    else
    {
        @Html.Partial("_NoCarAdded");
    }
</div>
<div class="overlay-add-car container-fluid clear-padding">

</div>
<script src="~/Scripts/MyCarScript.js"></script>

DriveHappy/DriveHappy.Web/Views/Owner/_NoCarAdded.cshtml
<div class="no-car">
    <figure class="no-car-figure">
        <img src="~/Content/images/Accident1.png" />
        <figcaption>No cars added yet</figcaption>
    </figure>
</div>